### ISSUE TITLE
Uncaught ReferenceError: store is not defined ?

### ISSUE THREAD

**Issue by repsorp** [JillzTom/c20-chrome-extension#1]
c20-chrome-extension no longer works...
Is there any way to fix this ?

error message:
Uncaught ReferenceError: store is not defined
Failed to load https://api.fixer.io/latest?base=USD: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://eefiefnpbjpomaclcmejknedafmemifp' is therefore not allowed access. The response had HTTP status code 404.
Uncaught (in promise) Error: Network Error

IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                                                                    This API endpoint is deprecated and has now been shut down. To keep using the Fixer API, please update your integration
to use the new Fixer API endpoint, designed as a simple drop-in replacement.                                                  You will be required to create an account at https://fixer.io and obtain an API access key.

Thanks

**Comment by jillztom** [comment]
Sure, I'll take a look at it now.

**Comment by jillztom** [comment]
Fixed! :)
